# Generated by Django 3.2.5 on 2021-07-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_time', models.CharField(blank=True, max_length=100, null=True)),
                ('frame_time_delta', models.IntegerField(blank=True, null=True)),
                ('frame_type', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_src', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_dst', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_src', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_dst', models.CharField(blank=True, max_length=100, null=True)),
                ('protocol', models.CharField(blank=True, max_length=100, null=True)),
                ('port_src', models.CharField(blank=True, max_length=100, null=True)),
                ('port_dst', models.CharField(blank=True, max_length=100, null=True)),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('frame_len', models.IntegerField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FrameCaptureConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_ip', models.CharField(default='10.0.3.15', max_length=100)),
                ('frames_number', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='HMMLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connexion', models.CharField(blank=True, max_length=100, null=True)),
                ('states', models.CharField(blank=True, max_length=100, null=True)),
                ('transition_matrix', models.CharField(blank=True, max_length=1000, null=True)),
                ('emission_matrix', models.CharField(blank=True, max_length=1000, null=True)),
                ('label', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HMMOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connexion', models.CharField(blank=True, max_length=100, null=True)),
                ('states', models.CharField(blank=True, max_length=100, null=True)),
                ('transition_matrix', models.CharField(blank=True, max_length=1000, null=True)),
                ('emission_matrix', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
