# Generated by Django 3.2.5 on 2021-07-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210708_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='postal',
        ),
    ]
